version: "3"


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
    volumes:
      - .:/src
    command: bash -c "alembic upgrade head && cd src && uvicorn app:app --host 0.0.0.0 --reload"
    ports:
      - "8000:8000"

  postgres:
    image: postgres:16.0
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "54321:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
